services:
  carpa-dev:
    image: carpa-dev:1.0.0
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=1
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - stack-net

networks:
  stack-net:
    external: true